## Numpy

In [1]:
from sklearn.utils.extmath import cartesian
import numpy as np
searchrange = 10
x = np.arange(-searchrange, searchrange)
y = np.arange(-searchrange, searchrange)
region = cartesian((x, y))   
region

array([[-10, -10],
       [-10,  -9],
       [-10,  -8],
       [-10,  -7],
       [-10,  -6],
       [-10,  -5],
       [-10,  -4],
       [-10,  -3],
       [-10,  -2],
       [-10,  -1],
       [-10,   0],
       [-10,   1],
       [-10,   2],
       [-10,   3],
       [-10,   4],
       [-10,   5],
       [-10,   6],
       [-10,   7],
       [-10,   8],
       [-10,   9],
       [ -9, -10],
       [ -9,  -9],
       [ -9,  -8],
       [ -9,  -7],
       [ -9,  -6],
       [ -9,  -5],
       [ -9,  -4],
       [ -9,  -3],
       [ -9,  -2],
       [ -9,  -1],
       [ -9,   0],
       [ -9,   1],
       [ -9,   2],
       [ -9,   3],
       [ -9,   4],
       [ -9,   5],
       [ -9,   6],
       [ -9,   7],
       [ -9,   8],
       [ -9,   9],
       [ -8, -10],
       [ -8,  -9],
       [ -8,  -8],
       [ -8,  -7],
       [ -8,  -6],
       [ -8,  -5],
       [ -8,  -4],
       [ -8,  -3],
       [ -8,  -2],
       [ -8,  -1],
       [ -8,   0],
       [ -8,   1],
       [ -8,

In [92]:
# import numpy as np
lx = np.arange(-10,10)
lx = lx[(lx >= 3) & (lx < 7)]
l = np.asarray([[(x,y) for x in lx] for y in lx])
print l.shape
c = (1./12.)*(1./12.)
f = np.apply_along_axis(lambda x: np.exp(-c*np.linalg.norm(x)**2), 2, l)

d = np.zeros((10,10))
#d[lx,lx] += f
d.round(2)

d[1:2,1:2]

(4, 4, 2)


array([[ 0.]])

In [ ]:
import numpy as np
np.random.seed(123)
r = np.random.uniform(-1,1,(10,2))
s = np.random.uniform(-1,1,(10,2))
r = np.ones((10,2))
r = np.ones((10,2))
print r.shape
print r
print np.sign(r)
print np.sign(s)
print (np.sign(r) == np.sign(s)).all(axis=1).mean()
np.linalg.norm(r)**2 / r.size 

In [ ]:
import numpy as np
x = np.exp(np.random.uniform(np.log(8),np.log(512),(100,))).astype(np.int)
x.sort()
x.tolist()

In [ ]:
import numpy as np
np.random.seed(123)
x = np.random.uniform(0,1,(10,2))
c = np.asarray([np.exp(-0.5*(a*a+b*b)) for a,b in x])
print x
print c

In [31]:
import numpy as np
from sklearn.utils.extmath import cartesian
x = np.arange(-10,10)
y = np.arange(-10,10)
x, y
np.dstack?
region = cartesian((x,y))
np.apply_along_axis(lambda x: x[0] + x[1], 1, region)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,
        -6,  -5,  -4,  -3,  -2,  -1,   0,   1, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,
         1,   2, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,
        -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5, -13, -12, -11,
       -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7, -1

## Decoretor 

In [ ]:
def deco(func):
    def show_args(a, b):
        print a , b
        return func(a, b)
    return show_args


@deco
def prod(x, y):
    return x * y


print prod(2, 3)

## Eigen

In [ ]:
import numpy as np
A = np.array([[0, 1./6, 0], [1, 1./3, 0.5], [0, 0.5, 0.5]])
l,v= np.linalg.eig(A)
#np.dot(v[2])/v[2]
#v[2]/v[2][0]
np.dot(A,v[:,2])/v[:,2]
v[:,2]/v[:,2][0]

In [ ]:
import numpy as np
ratio = 0.1
l = []
for i in range(10000):
    x = np.random.choice([0, 1], p=[1.-ratio, ratio])
    l.append(x)
print np.asarray(l).sum()

In [ ]:
%pdb on

In [ ]:
import pandas as pd
import numpy as np

def main():
    N=5
    df0 = pd.DataFrame(range(N))
    np.sqrt(((df0 - df0.mean())**2).sum()/(N-1)) 
    df0['str']=df0[[0]].applymap(str)
    x = y
    df0

In [ ]:
%debug(main())

## Pandas

In [1]:
import pandas as pd
import numpy as np
N=5
df0 = pd.DataFrame(range(N))
np.sqrt(((df0 - df0.mean())**2).sum()/(N-1)) 
df0['str']=df0[[0]].applymap(str)
df0
x = y
df0.std()
df0[0].map(str).map(str)

NameError: name 'y' is not defined

In [2]:
import pandas as pd
df0 = pd.DataFrame([[1,2,'x'],[3,4,'z'],[3,4,'z']]).set_index([[3,4,5]])
g = pd.groupby(df0, by=0)
g.get_group(1)

0  1  2
3  1  2  x

In [ ]:
%pdb on

In [ ]:
import os
def join():
    df0[['str']].applymap(lambda x: os.path.join('/work/',x))

In [ ]:
import pandas as pd
l0 = [(1,2),(3,4)]
l1 = [(4,5),(5,6)]
df = pd.DataFrame(zip(l0))
df.to_csv('tmp.csv', sep='\t')
df1 = pd.read_csv('tmp.csv', sep='\t', index_col=0, converters={'0': eval})
print df1['0'][0]
print type(df1['0'][0])
df1.describe(include='all')
print pd.__version__

In [ ]:
import pandas as pd
df = pd.DataFrame(columns=['x','y'])
df.append(pd.DataFrame([[0,1]]))
df

##  文字列操作

In [ ]:
import re
def get_default(S):
    try:
        default = re.search('\(.*\)', re.search('%.*%',S).group()).group().replace('(','').replace(')','')
    except:
        default = re.search('%.*%',S).group()
    return default

def get_tag(S):
    try:
        tag = re.sub('\(.*\)','',re.search('%.*%',S).group()).replace('%','')
    except:
        tag = None
    return tag


def replace_string(srcstr, replacelist):
    dststr=''
    for x in srcstr.splitlines():
        tag = get_tag(x)
        if tag is not None:
            if tag in replacelist.keys():
                dststr += re.sub('%.*%',replacelist[tag],x) + '\n'
            else:
                dststr += re.sub('%.*%',get_default(x),x) + '\n'
        else:
            dststr += x + '\n'
    return dststr.rstrip('\n')

def test():
    replacelist={'NAME':'T.Sato'}
    S='my name is %NAME(K.Ogawa)%\n'
    S+='I live in %PLACE(Yokohama)%\n'
    S+='%%%%'
    replaced = replace_string(S, replacelist)
    answer  ='my name is T.Sato\n'
    answer +='I live in Yokohama\n'
    answer +='%%%%'
    print 'source:'
    print S
    print 'replaced:'
    print replaced
    print 'answer:'
    print answer
    print 
    if answer == replaced:
        return 'TEST PASSED'
    else:
        return 'TEST FAILED'

print test()

## debugの使い方

In [ ]:
def f(a, b):
    a += 1
    b += 2
    return a + b

def g(a, b, c):
    a = f(a,b)
    b = f(b,c)
    return a + b

In [ ]:
%debug(g(1,2,3))
# s: proceed one step (enter funciton)
# n: proceed one step (don't enter function)
# a: print all local variable
# c: continue upto breakpoint

http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/ipython.html

http://qiita.com/ynakayama/items/c51c2b6d6a3818bdb63f

In [ ]:
import numpy as np
np.random.seed(123)
x = np.random.randint(0,10,(5,2))
y = np.random.randint(0,10,(5,2))

def f(x,y):
    return x[0] + y[1], x[1] + y[0]
print x
print y
z = np.asarray([x,y])
zt = np.ndarray.transpose(z,(1,0,2))

def defprint(x):
    print ':', x
    return x

def defprint2(x,y):
    print '1:', x
    print '2:', y
    return x + y

np.asarray([f(x,y) for x,y in zt])
#np.apply_over_axes(defprint2, zt, [0,1])

In [ ]:
np.fromiter?
np.frompyfunc?

## TODO
#### doctest
#### unittest