## Decoretor 

In [1]:
def deco(func):
    def show_args(a, b):
        print a , b
        return func(a, b)
    return show_args


@deco
def prod(x, y):
    return x * y


print prod(2, 3)

2 3
6


## Eigen

In [36]:
import numpy as np
A = np.array([[0, 1./6, 0], [1, 1./3, 0.5], [0, 0.5, 0.5]])
l,v= np.linalg.eig(A)
#np.dot(v[2])/v[2]
#v[2]/v[2][0]
np.dot(A,v[:,2])/v[:,2]
v[:,2]/v[:,2][0]

array([ 1.,  6.,  6.])

In [87]:
import numpy as np
ratio = 0.1
l = []
for i in range(10000):
    x = np.random.choice([0, 1], p=[1.-ratio, ratio])
    l.append(x)
print np.asarray(l).sum()

945


In [ ]:
%pdb on

In [ ]:
import pandas as pd
import numpy as np

def main():
    N=5
    df0 = pd.DataFrame(range(N))
    np.sqrt(((df0 - df0.mean())**2).sum()/(N-1)) 
    df0['str']=df0[[0]].applymap(str)
    x = y
    df0

In [ ]:
%debug(main())

## Pandas

In [ ]:
import pandas as pd
import numpy as np
N=5
df0 = pd.DataFrame(range(N))
np.sqrt(((df0 - df0.mean())**2).sum()/(N-1)) 
df0['str']=df0[[0]].applymap(str)
df0
x = y
df0.std()
df0[0].map(str).map(str)

In [ ]:
import pandas as pd
df0 = pd.DataFrame([[1,2,'x'],[3,4,'z'],[3,4,'z']]).set_index([[3,4,5]])
g = pd.groupby(df0, by=0)
g.get_group(1)

In [ ]:
%pdb on

In [ ]:
import os
def join():
    df0[['str']].applymap(lambda x: os.path.join('/work/',x))

##  文字列操作

In [2]:
import re
def get_default(S):
    try:
        default = re.search('\(.*\)', re.search('%.*%',S).group()).group().replace('(','').replace(')','')
    except:
        default = re.search('%.*%',S).group()
    return default

def get_tag(S):
    try:
        tag = re.sub('\(.*\)','',re.search('%.*%',S).group()).replace('%','')
    except:
        tag = None
    return tag


def replace_string(srcstr, replacelist):
    dststr=''
    for x in srcstr.splitlines():
        tag = get_tag(x)
        if tag is not None:
            if tag in replacelist.keys():
                dststr += re.sub('%.*%',replacelist[tag],x) + '\n'
            else:
                dststr += re.sub('%.*%',get_default(x),x) + '\n'
        else:
            dststr += x + '\n'
    return dststr.rstrip('\n')

def test():
    replacelist={'NAME':'T.Sato'}
    S='my name is %NAME(K.Ogawa)%\n'
    S+='I live in %PLACE(Yokohama)%\n'
    S+='%%%%'
    replaced = replace_string(S, replacelist)
    answer  ='my name is T.Sato\n'
    answer +='I live in Yokohama\n'
    answer +='%%%%'
    print 'source:'
    print S
    print 'replaced:'
    print replaced
    print 'answer:'
    print answer
    print 
    if answer == replaced:
        return 'TEST PASSED'
    else:
        return 'TEST FAILED'

print test()

source:
my name is %NAME(K.Ogawa)%
I live in %PLACE(Yokohama)%
%%%%
replaced:
my name is T.Sato
I live in Yokohama
%%%%
answer:
my name is T.Sato
I live in Yokohama
%%%%

TEST PASSED


## debugの使い方

In [ ]:
def f(a, b):
    a += 1
    b += 2
    return a + b

def g(a, b, c):
    a = f(a,b)
    b = f(b,c)
    return a + b

In [ ]:
%debug(g(1,2,3))
# s: proceed one step (enter funciton)
# n: proceed one step (don't enter function)
# a: print all local variable
# c: continue upto breakpoint

http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/ipython.html

http://qiita.com/ynakayama/items/c51c2b6d6a3818bdb63f

In [71]:
import numpy as np
np.random.seed(123)
x = np.random.randint(0,10,(5,2))
y = np.random.randint(0,10,(5,2))

def f(x,y):
    return x[0] + y[1], x[1] + y[0]
print x
print y
z = np.asarray([x,y])
zt = np.ndarray.transpose(z,(1,0,2))

def defprint(x):
    print ':', x
    return x

def defprint2(x,y):
    print '1:', x
    print '2:', y
    return x + y

np.asarray([f(x,y) for x,y in zt])
#np.apply_over_axes(defprint2, zt, [0,1])

[[2 2]
 [6 1]
 [3 9]
 [6 1]
 [0 1]]
[[9 0]
 [0 9]
 [3 4]
 [0 0]
 [4 1]]


array([[ 2, 11],
       [15,  1],
       [ 7, 12],
       [ 6,  1],
       [ 1,  5]])

In [68]:
np.fromiter?
np.frompyfunc?